pub mod assets;
pub mod bangumi_subjects;
pub mod cache_entries;
pub mod deezer_albums;
pub mod deezer_artists;
pub mod deezer_tracks;
pub mod douban_subjects;
pub mod fanart_assets;
pub mod holiday_years;
pub mod lrclib_lyrics;
pub mod musicbrainz_artists;
pub mod musicbrainz_recordings;
pub mod musicbrainz_releases;
pub mod nominatim_geocode;
pub mod omdb_titles;
pub mod openmeteo_forecasts;
pub mod qidian_books;
pub mod rate_limit_buckets;
pub mod service_keys;
pub mod spotify_albums;
pub mod spotify_artists;
pub mod spotify_token_cache;
pub mod spotify_tracks;
pub mod thetvdb_episodes;
pub mod thetvdb_series;
pub mod thetvdb_token_cache;
pub mod tmdb_images;
pub mod tmdb_movies;
pub mod tmdb_objects;
pub mod wikipedia_summaries;

pub use assets::Entity as Assets;
pub use bangumi_subjects::Entity as BangumiSubjects;
pub use cache_entries::Entity as CacheEntries;
pub use deezer_albums::Entity as DeezerAlbums;
pub use deezer_artists::Entity as DeezerArtists;
pub use deezer_tracks::Entity as DeezerTracks;
pub use douban_subjects::Entity as DoubanSubjects;
pub use fanart_assets::Entity as FanartAssets;
pub use holiday_years::Entity as HolidayYears;
pub use lrclib_lyrics::Entity as LrclibLyrics;
pub use musicbrainz_artists::Entity as MusicbrainzArtists;
pub use musicbrainz_recordings::Entity as MusicbrainzRecordings;
pub use musicbrainz_releases::Entity as MusicbrainzReleases;
pub use nominatim_geocode::Entity as NominatimGeocode;
pub use omdb_titles::Entity as OmdbTitles;
pub use openmeteo_forecasts::Entity as OpenmeteoForecasts;
pub use qidian_books::Entity as QidianBooks;
pub use rate_limit_buckets::Entity as RateLimitBuckets;
pub use service_keys::Entity as ServiceKeys;
pub use spotify_albums::Entity as SpotifyAlbums;
pub use spotify_artists::Entity as SpotifyArtists;
pub use spotify_token_cache::Entity as SpotifyTokenCache;
pub use spotify_tracks::Entity as SpotifyTracks;
pub use thetvdb_episodes::Entity as ThetvdbEpisodes;
pub use thetvdb_series::Entity as ThetvdbSeries;
pub use thetvdb_token_cache::Entity as ThetvdbTokenCache;
pub use tmdb_images::Entity as TmdbImages;
pub use tmdb_movies::Entity as TmdbMovies;
pub use tmdb_objects::Entity as TmdbObjects;
pub use wikipedia_summaries::Entity as WikipediaSummaries;
